### ISSUE TITLE
Does not build correctly

### ISSUE THREAD

**Issue by astout** [mongoose-os-apps/example-wifi-scan-js#1]
If I run a build of this example, it seems to build but doesn't do anything. I inspected the build files and there's no api_wifi.js in there. I am guessing you are building against a newer version of mongoose than I am. Is there a version of mongoose available where I can get support for this? I really want the ability to do this with JS. Any recommendation?

**Comment by rojer** [comment]
what is the output of your `mos --version`?

**Comment by astout** [comment]
```
The Mongoose OS command line tool
Version: 1.15
Build ID: 20170907-130858/1.15@8f8f002d+
Update channel: release
```

**Comment by rojer** [comment]
right. this was added after the release, you'll need to switch to `latest` to use it.

**Comment by cpq** [comment]
`mos update latest`

**Comment by rojer** [comment]
it's not an issue with the app itself, so - closing.

**Comment by astout** [comment]
You guys are great. Thank you!
